<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListWithCategories()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT p,c
                    FROM AppBundle:Product p
                    JOIN p.category c');
        return $query->getResult();

    }

}
